Version 1
vremere-a/Internet-Shop.vremere pull request #1
Opened 2020-09-03 12:17 UTC by vremere-a

2020-09-03 12:37 UTC, KostiantynVorobiov approved these changes
As for me OK

2020-09-03 13:53 UTC, KseniiaMakarova requested changes
remove classes with solution from `master` branch

and here, in this PR, let's remove `<dependencies>` block from `pom.xml`
we do not use dependencies yet

2020-09-03 13:53 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/Main.java
> +        productService.deleteById(2L);
save your products to variables and use `someProduct.getId()` instead everywhere

2020-09-03 13:53 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +        }
the logic is ok, but let's use Stream API

2020-09-03 13:53 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +        return null;
return `product` in each case

2020-09-03 13:53 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +        return true;
we can use `removeIf()` on storage

2020-09-03 13:53 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/Order.java
> +    }
the id is set in Storage class
same for other models

2020-09-03 13:53 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/Product.java
>      private BigDecimal price;
let's have `double` here for now

2020-09-03 13:53 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/ProductDao.java
> +    Optional<Product> geById(Long productId);
```suggestion
    Optional<Product> getById(Long productId);
```

2020-09-03 16:43 UTC, vremere-a commented on src/main/java/com/internet/shop/Main.java
> +        productService.deleteById(2L);
like this
Product playStation =  productService.create(new Product("PS4", 500));

2020-09-03 16:46 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +        }
done

2020-09-03 16:46 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +        return null;
ok

2020-09-03 16:50 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +        return true;
done

2020-09-03 16:55 UTC, vremere-a commented on src/main/java/com/internet/shop/model/Order.java
> +    }
done. changed also in Cart

2020-09-03 16:56 UTC, vremere-a commented on src/main/java/com/internet/shop/model/Product.java
>      private BigDecimal price;
done

2020-09-03 17:45 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/ProductDao.java
> +    Optional<Product> geById(Long productId);
done

2020-09-03 17:52 UTC, vremere-a commented on src/main/java/com/internet/shop/Main.java
> +        productService.deleteById(2L);
done.

2020-09-04 06:11 UTC, KseniiaMakarova requested changes

2020-09-04 06:11 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/Main.java
> +        productService.deleteById(2L);
```suggestion
        productService.deleteById(nintendo.getId());
```

2020-09-04 06:11 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +                .findFirst().get();
where are you updating?

let's create IntStream of indices, than filter out only those indices on which there are elements with the same id
then for each of the remaining indices, replace the element with our `product`

2020-09-04 06:11 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +        return true;
too much redundant code
`removeIf()` already iterates through all elements and returns boolean

2020-09-04 06:11 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/Order.java
> +        this.userId = userId;
let's initialize `products` in the constructor

2020-09-04 06:11 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/ShoppingCart.java
> +        this.userId = userId;
same

2020-09-04 08:22 UTC, KseniiaMakarova approved these changes

2020-09-05 07:38 UTC, merged