Homework 32
vremere-a/Internet-Shop.vremere pull request #12
Opened 2020-09-24 14:03 UTC by vremere-a

2020-09-24 14:28 UTC, fyarkiy commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +        return Optional.of(order);
ofNullable?

2020-09-24 14:30 UTC, fyarkiy commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +        create(order);
What does this method do?

2020-09-24 14:31 UTC, SetMyDream approved these changes
Good job!
Especially if it works properly)

2020-09-24 14:31 UTC, SetMyDream commented on src/main/java/com/internet/shop/model/Order.java
> +    private Long orderId;
good practice, I have taken note and used in my project)

2020-09-24 14:31 UTC, SetMyDream commented on src/main/java/com/internet/shop/model/User.java
> +    public User(Long id, String name, String surname,
maybe if you have such a many constructors, you need builder instead? I`m not sure

2020-09-24 14:34 UTC, fyarkiy commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +        create(order);
Why do you "create" order? deleteById should not delete an order. As I understand you tried to remove products from order and replace them with others - but you don't have to create new order - it seems to me this line is redundant

2020-09-24 14:34 UTC, vremere-a commented on src/main/java/com/internet/shop/model/User.java
> +    public User(Long id, String name, String surname,
ok

2020-09-24 14:35 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +        create(order);
ok. I think about this

2020-09-24 14:37 UTC, fyarkiy commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            return statement.executeUpdate() == 1;
you will return false here if there are several lines (products) in the order. Discussed with Sofia on Q&A and have similar comment from Roman: create int variable and accumulate there the result of statement.executeUpdate. Return this int > 0. The same in other similar returns below...

2020-09-24 14:37 UTC, vremere-a commented on src/main/java/com/internet/shop/model/Order.java
> +    private Long orderId;
👍

2020-09-24 14:37 UTC, fyarkiy commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            throw new DataProcessingException("Can't delete products from order", e);
you can add order # in message

2020-09-24 14:37 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +        return Optional.of(order);
🤷‍♂️

2020-09-24 14:39 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            throw new DataProcessingException("Can't delete products from order", e);
👍 done

2020-09-24 14:40 UTC, fyarkiy commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            for (int i = 0; i < order.getProducts().size(); i++) {
As an option - for (Product product : order.getProducts()) {...

2020-09-24 14:40 UTC, fyarkiy commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            throw new DataProcessingException("insert products to Order is failed!", e);
you might add order # in message...

2020-09-24 14:41 UTC, fyarkiy commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +        Product product;
you can do this declaration below on line 154 on the same time with initialisation.

2020-09-24 14:42 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            for (int i = 0; i < order.getProducts().size(); i++) {
I know but, that's comfy for my🙂

2020-09-24 14:42 UTC, fyarkiy commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +        ShoppingCart shoppingCart = new ShoppingCart();
you can do this on line 29 with initialisation

2020-09-24 14:42 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            throw new DataProcessingException("insert products to Order is failed!", e);
done

2020-09-24 14:43 UTC, fyarkiy commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +                    "SELECT * FROM shopping_carts WHERE user_id = ?");
do you think it's worthwhile to do check for "deleted"?

2020-09-24 14:44 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +        Product product;
ok

2020-09-24 14:44 UTC, fyarkiy commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +        return Optional.of(shoppingCart);
ofNullable?

2020-09-24 14:46 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +                    "SELECT * FROM shopping_carts WHERE user_id = ?");
yes. it's necessary for working app

2020-09-24 14:46 UTC, fyarkiy commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +            return statement.executeUpdate() == 1;
will return always failed - discussed with Sofia. Do through extra variable as I put above

2020-09-24 14:47 UTC, fyarkiy commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +            throw new DataProcessingException("Can't delete cart ", e);
add to message cart number

2020-09-24 14:47 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +        return Optional.of(shoppingCart);
done

2020-09-24 14:49 UTC, fyarkiy commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +                + "ON shopping_carts_products.product_id = products.product_id "
as the name of variable are the same you can use USING(product_id) instead of ON. 
Not critical - just a hint.
But if you don't use this - "from shopping_carts_products AS scp", "products AS p"...

2020-09-24 14:50 UTC, fyarkiy commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +        return Optional.of(user);
if wrong user - you might get npe... 
ofNullable?

2020-09-24 14:50 UTC, fyarkiy commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +        return Optional.of(user);
ofNullable...?

2020-09-24 14:51 UTC, fyarkiy commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +            return statement.executeUpdate() == 1;
>0...

2020-09-24 14:51 UTC, fyarkiy commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +                + "ON users_roles.role_id = roles.role_id WHERE users_roles.user_id = ?";
users_roles AS ur...

2020-09-24 14:52 UTC, fyarkiy approved these changes

2020-09-24 14:52 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +            return statement.executeUpdate() == 1;
clear

2020-09-24 14:53 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +            throw new DataProcessingException("Can't delete cart ", e);
done

2020-09-24 14:53 UTC, fyarkiy commented
Well done!!!

2020-09-24 14:53 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +                + "ON shopping_carts_products.product_id = products.product_id "
ok. I understand

2020-09-24 14:54 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +        return Optional.of(user);
done

2020-09-24 14:54 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +        return Optional.of(user);
done

2020-09-24 14:55 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +            return statement.executeUpdate() == 1;
clear

2020-09-24 14:55 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +                + "ON users_roles.role_id = roles.role_id WHERE users_roles.user_id = ?";
ok

2020-09-25 07:48 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +        Product product;
погоджуюсь, варто оголосити там де ініціалізовуєш

2020-09-25 07:48 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +                orders.add(getOrderFromResultSet(resultSet));
тут ми викликаємо метод getOrderFromResultSet в якому знову відкривається connection
виходить що в нас в connection відкривається новий connection - а це не ок практика
спробуй позбутись цього у всіх методах де це зустрічається

2020-09-25 07:48 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            throw new DataProcessingException("Can't get product by " + userId + " !", ex);
```suggestion
            throw new DataProcessingException("Can't get order by " + userId + " !", ex);
```

2020-09-25 07:48 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +        Order order = new Order();
тут краще не ініціалізовувати замовлення, а залишити як Order order = null;
тоді внизу варто додати перевірку на те чи він не null

2020-09-25 07:48 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +        order.setProducts(getProductsFromOrder(order.getOrderId()));
цю строку коду можна перенести на верх метода:
List<Product> products = getProductsFromOrder(order.getOrderId())

2020-09-25 07:48 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +    public Order update(Order order) {
при оновленні ми не повинні видаляти замовлення, ми повинні видаляти список продуктів в замовленні та додавати новий

2020-09-25 07:48 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            return statement.executeUpdate() == 1;
так, краще присвоїти результат для змінної та порівняти з 0

2020-09-25 07:48 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +        List<Order> orders = new ArrayList<>();
переглянь уважно цей метод, зараз ти двічі засечуєш продукти для ордера. Але коли ти позбудешся connection в connection це повинно виправитись

2020-09-25 07:48 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +        ShoppingCart shoppingCart = new ShoppingCart();
знову тех саме щодо ініціалізації null

2020-09-25 07:48 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +                    "SELECT * FROM shopping_carts WHERE cart_id = ?");
and deleted = false

2020-09-25 07:48 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +        String query = "DELETE FROM shopping_carts WHERE cart_id=?";
тут ми видаляємо все з суміжної таблиці. А як щодо самої корзини?

2020-09-25 07:48 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +                + "WHERE shopping_carts_products.cart_id = ?";
такі запити можна спрощувати:
```suggestion
        String query = "SELECT * FROM shopping_carts_products cp "
                + "INNER JOIN products p"
                + "ON cp.product_id = p.product_id "
                + "WHERE cp.cart_id = ?";
```

2020-09-25 07:48 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +                    "INSERT INTO users(user_name, user_surname, email, login, password)\n"
краще виносити запит в окрему змінну

2020-09-25 07:48 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +                + "INNER JOIN users_roles \n"
чи варто тут використовувати JOIN якщо нижче ми викликаємо окремий метод, який дістає ролі

2020-09-25 07:48 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +                    "UPDATE users SET user_name = ?,"
чи варто апдейтити ролі?

2020-09-25 07:48 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +                User user = getUserFromResultSet(resultSet);
де ми дістаємо ролі для юзерів?

2020-09-25 12:14 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +        Product product;
done

2020-09-25 12:17 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +                    "SELECT * FROM shopping_carts WHERE user_id = ?");
done

2020-09-25 12:20 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +                orders.add(getOrderFromResultSet(resultSet));
Но я не открываю в методе getOrderFromResultSet новый connection 

private Order getOrderFromResultSet(ResultSet resultSet) throws SQLException {
        Long orderId = resultSet.getLong("order_id");
        Long userId = resultSet.getLong("user_id");
        List<Product> products = getProductsFromOrder(orderId);
        return new Order(orderId, userId, products);
    }

2020-09-25 12:20 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +                orders.add(getOrderFromResultSet(resultSet));
или я не правильно понял

2020-09-25 12:21 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            throw new DataProcessingException("Can't get product by " + userId + " !", ex);
done

2020-09-25 12:22 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +        Order order = new Order();
done

2020-09-25 12:22 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +        Order order = new Order();
if (order != null) {
            order.setProducts(getProductsFromOrder(order.getOrderId()));
        }
        return Optional.ofNullable(order);

2020-09-25 12:29 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +        order.setProducts(getProductsFromOrder(order.getOrderId()));
done

2020-09-25 12:36 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +    public Order update(Order order) {
clear

2020-09-25 12:38 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            return statement.executeUpdate() == 1;
done

2020-09-25 12:51 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +        List<Order> orders = new ArrayList<>();
🤷‍♂️ не совсем понял. вроде нет connection в connection

2020-09-25 12:52 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +        ShoppingCart shoppingCart = new ShoppingCart();
done

2020-09-25 12:52 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +                    "SELECT * FROM shopping_carts WHERE cart_id = ?");
done

2020-09-25 12:57 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +        String query = "DELETE FROM shopping_carts WHERE cart_id=?";
ok

2020-09-25 12:58 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +                + "WHERE shopping_carts_products.cart_id = ?";
ok. next time will use

2020-09-25 13:01 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +                    "INSERT INTO users(user_name, user_surname, email, login, password)\n"
done

2020-09-25 13:09 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +                + "INNER JOIN users_roles \n"
ok

2020-09-25 13:24 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +                User user = getUserFromResultSet(resultSet);
add
for (User user : users) {
            user.setRoles(getRolesOfUser(user.getId()));
        }

2020-09-25 13:24 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +                    "UPDATE users SET user_name = ?,"
ok

2020-09-28 15:37 UTC, KseniiaMakarova requested changes

2020-09-28 15:37 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +                orders.add(getOrderFromResultSet(resultSet));
inside `getOrderFromResultSet()` you are calling `getProductsFromOrder()` and there you open new Connection

2020-09-28 15:37 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +        List<Order> orders = new ArrayList<>();
inside `getOrderFromResultSet()` you are calling `getProductsFromOrder()` and there you open new Connection
and you are also setting product twice for each order

2020-09-28 15:37 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            throw new DataProcessingException("Can't to get all carts!", e);
why carts?

2020-09-28 15:37 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            order.getProducts().addAll(getProductsFromOrder(order.getOrderId()));
```suggestion
            order.setProducts(getProductsFromOrder(order.getOrderId()));
```

2020-09-28 15:37 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +        user.setRoles(getRolesOfUser(user.getId()));
seems that your `user` already has roles, no need to set them and call `getRolesOfUser()`

2020-09-29 13:25 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            throw new DataProcessingException("Can't to get all carts!", e);
ups!
done

2020-09-29 13:32 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            order.getProducts().addAll(getProductsFromOrder(order.getOrderId()));
done

2020-09-29 14:00 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +                orders.add(getOrderFromResultSet(resultSet));
done

2020-09-29 14:08 UTC, merged