Homework 28.2
vremere-a/Internet-Shop.vremere pull request #9
Opened 2020-09-15 10:38 UTC by vremere-a

2020-09-15 10:43 UTC, Rudiachenko requested changes

2020-09-15 10:43 UTC, Rudiachenko commented on src/main/webapp/WEB-INF/views/admin/allProductsAdmin.jsp
>  </html>
No new line at end of file

2020-09-15 10:43 UTC, Rudiachenko commented on src/main/webapp/WEB-INF/views/admin/allOrdersAdmin.jsp
>  </html>
No new line at end of file

2020-09-15 10:44 UTC, voloshynamaryna11 reviewed
done

2020-09-15 10:44 UTC, voloshynamaryna11 commented on src/main/java/com/internet/shop/controllers/cart/AddProductToShoppingCartController.java
> +    private static final String USER_ID = "user_id";
у меня у самой так же, но скорее всего скажут убрать это поле

2020-09-15 10:46 UTC, vremere-a commented on src/main/webapp/WEB-INF/views/admin/allProductsAdmin.jsp
>  </html>
done

2020-09-15 10:47 UTC, vremere-a commented on src/main/webapp/WEB-INF/views/admin/allOrdersAdmin.jsp
>  </html>
done

2020-09-15 10:47 UTC, vremere-a commented on src/main/java/com/internet/shop/controllers/cart/AddProductToShoppingCartController.java
> +    private static final String USER_ID = "user_id";
Оки. посмотрим.

2020-09-16 05:30 UTC, KseniiaMakarova requested changes

2020-09-16 05:30 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/cart/AddProductToShoppingCartController.java
> +        Product product = productService.getById(userId);
reconsider line 29 please

2020-09-16 05:30 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/cart/DeleteProductsFromShoppingCartController.java
> +        Product product = productService.getById(userId);
same for line 28 here

2020-09-16 05:30 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/security/implementations/AuthenticationServiceImpl.java
> +        User userFromDB = userService.findByLogin(login).orElseThrow();
```suggestion
        Optional<User> userFromDB = userService.findByLogin(login);
```

2020-09-16 05:30 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/security/implementations/AuthenticationServiceImpl.java
>          if (userFromDB.getPassword().equals(password)) {
let's add one more condition here

2020-09-16 05:30 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/admin/allOrdersAdmin.jsp
> +                <c:out value="${order.products}"/>
are you sure you need this column? you already have `details` button

2020-09-16 05:30 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/index.jsp
> +            <a class="dropdown-item" href="${pageContext.request.contextPath}/admin/products">PRODUCT</a>
```suggestion
            <a class="dropdown-item" href="${pageContext.request.contextPath}/admin/orders">VIEW ORDERS</a>
            <a class="dropdown-item" href="${pageContext.request.contextPath}/admin/products">MANAGE PRODUCTS</a>
```

what do you think?

2020-09-16 05:36 UTC, vremere-a commented on src/main/java/com/internet/shop/controllers/cart/AddProductToShoppingCartController.java
> +        Product product = productService.getById(userId);
done. 
add  
String id = req.getParameter("id");
Long productId = Long.valueOf(id);

2020-09-16 05:36 UTC, vremere-a commented on src/main/java/com/internet/shop/controllers/cart/DeleteProductsFromShoppingCartController.java
> +        Product product = productService.getById(userId);
done

2020-09-16 05:38 UTC, vremere-a commented on src/main/java/com/internet/shop/security/implementations/AuthenticationServiceImpl.java
> +        User userFromDB = userService.findByLogin(login).orElseThrow();
done

2020-09-16 05:43 UTC, vremere-a commented on src/main/java/com/internet/shop/security/implementations/AuthenticationServiceImpl.java
>          if (userFromDB.getPassword().equals(password)) {
done

2020-09-16 05:45 UTC, vremere-a commented on src/main/webapp/WEB-INF/views/admin/allOrdersAdmin.jsp
> +                <c:out value="${order.products}"/>
agree

2020-09-16 05:46 UTC, vremere-a commented on src/main/webapp/WEB-INF/views/index.jsp
> +            <a class="dropdown-item" href="${pageContext.request.contextPath}/admin/products">PRODUCT</a>
you are right!
done

2020-09-16 05:54 UTC, KseniiaMakarova approved these changes

2020-09-16 05:54 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/admin/allOrdersAdmin.jsp
> -        </td>
let's also remove `<th scope="col">Items</th>` this part above

2020-09-16 08:52 UTC, merged